### ISSUE TITLE
Discord buttons don’t work with slash commands

### ISSUE THREAD

**Issue by cainthebest** [AlexzanderFlores/WOKCommands#107]
I cannot go into much detail due to the fact i am unable to find the cause of the issue but if you return a embed or text with a button it throws a error

**Comment by pazzazzo** [comment]
https://github.com/AlexzanderFlores/WOKCommands/pull/108

**Comment by cainthebest** [comment]
@pazzazzo #108 what do you mean by interaction not being a slash command as the bug that i get is that when trying to send a button with a embed on the slash return it errors out. But if the button is removed from the embed const the slash command works fine

**Comment by pazzazzo** [comment]
@cainthebest Sorry, I did not understand.  I do not speak English

**Comment by cainthebest** [comment]
what language?

**Comment by pazzazzo** [comment]
French

**Comment by cainthebest** [comment]
@pazzazzo 
Ce que je disais, c’est que l’interaction échoue si vous envoyez une incorporation avec un bouton en tant que commande de barre oblique

Est-ce que tu comprends?
aussi s’il vous plaît utiliser pas de mots raccourcis afin que je puisse comprendre votre réponse

**Comment by pazzazzo** [comment]
On ne peut pas envoyer de button dans un reply d'interaction, discord lui même ne le permet pas

**Comment by cainthebest** [comment]
Je peux montrer que certains bots peuvent le faire. Je pensais que c’était possible de le faire, mais je vais y jeter un coup d’œil plus. la seule raison pour laquelle je ne peux pas lire ceci est parce que je n’ai pas longtemps commencé ts et je sais surtout js

**Comment by pazzazzo** [comment]
Peut-tu m'écrire en anglais car certains mots sont mal traduits donc je ne comprends pas

**Comment by cainthebest** [comment]
sorry bing translate lol
but what i said was I can show that some bots can do this. I thought it was possible to do it, but I'll take a look at it more. the only reason I can't read this is because I didn't start ts long ago and I know mostly js

**Comment by pazzazzo** [comment]
Ho, Okay

**Comment by cainthebest** [comment]
Heres a example 
https://user-images.githubusercontent.com/75994858/120243139-b7b8fb80-c25e-11eb-887d-8eb4b0a2b325.MOV

**Comment by pazzazzo** [comment]
Can you send a error please?

**Comment by cainthebest** [comment]
i cant send a error now as i deleted my version of that vid but yeah its all explained here https://discord.com/developers/docs/interactions/message-components#what-are-components

**Comment by wrssmithjr04** [comment]
Please look at #109

**Comment by cferreras** [comment]
`C:\Users\User\Desktop\discord-bot\node_modules\wokcommands\dist\SlashCommands.js:63
                    command = name.toLowerCase();
                                   ^

TypeError: Cannot read property 'toLowerCase' of undefined`

Why?

**Comment by cferreras** [comment]
> ```
> C:\Users\User\Desktop\discord-bot\node_modules\wokcommands\dist\SlashCommands.js:63
>                     command = name.toLowerCase();
>                                    ^
> 
> TypeError: Cannot read property 'toLowerCase' of undefined
> ```
> 
> Why?

If I remove the .toLowerCase() method, it works correctly 😂

**Comment by cainthebest** [comment]
@cferreras Isn't this a different issue?
