### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by cainthebest** [AlexzanderFlores/WOKCommands#116]
Have a types folder with *d.ts with declarations for WOKcommands modules to start working towards ts support

**Comment by cursedstuff** [comment]
@AlexzanderFlores Can you close issues that are no longer active or ones like this that are resolved? Helps clean out issues that we don't need to focus on. Thanks.

**Comment by cainthebest** [comment]
Ah its okay ill close the issue i can see there are type decorations, forgot this issue was open due to me working on stuff that excludes d.js etc
