### ISSUE TITLE
Help command not working

### ISSUE THREAD

**Issue by ehAsuna** [AlexzanderFlores/WOKCommands#125]
Error ~> https://sourceb.in/uut8qUq8K8
My code ~>https://sourceb.in/jYLaEA90yC
  Issue: Everytime I try to react on the help command this is error is thrown.
  I've checked over my code and cannot see why it is doing this, I've even tried re-writing some.

**Comment by Wolletje01** [comment]
I have found the issue:

In your node_modules and thn wokcommands and then command then help then !Reactionlisteren
You have the change the 139th line to  
```js
_this.message.edit('', { embed: _this.embed });
```
instead of
```js
_this.message.edit( _this.embed );
```

**Comment by ehAsuna** [comment]
> I have found the issue:
> 
> In your node_modules and thn wokcommands and then command then help then !Reactionlisteren
> You have the change the 139th line to
> 
> ```js
> _this.message.edit('', { embed: _this.embed });
> ```
> 
> instead of
> 
> ```js
> _this.message.edit( _this.embed );
> ```

All I had to do was set the name on the help commands using, 
```.setDisplayName('Ahega0')```
