### ISSUE TITLE
Slash delete command not recognizing global commands

### ISSUE THREAD

**Issue by DFDFilms** [AlexzanderFlores/WOKCommands#147]
When running prefix + slash. It shows the correct embed, but does not list the global command ids (image 1). 
![image](https://user-images.githubusercontent.com/84550788/132938417-c4a54bfb-0699-4d82-9789-a0c3a8f8bc77.png)
![image](https://user-images.githubusercontent.com/84550788/132938433-a4d1a755-884a-433e-be36-493de382fdfc.png)

It has worked for me once, so you could assume the actually deletion is working just not finding of the IDs

**Comment by BlakeH2208** [comment]
It has been fixed in the second to most recent update

**Comment by cursorsdottsx** [comment]
@DFDFilms Close this issue as it has been resolved. Work to keep this repository clean!

**Comment by tippfehlr** [comment]
> 

Yes, please!
@DFDFilms @AlexzanderFlores
