### ISSUE TITLE
setDefaultPrefix doesn't work

### ISSUE THREAD

**Issue by aradclash3** [AlexzanderFlores/WOKCommands#154]
I am making a new bot and while testing my bot I discovered that set default prefix doesn't work

**Comment by aradclash3** [comment]
I just discovered that none of the prefixes work
not the '!' which is the default default prefix

**Comment by aradclash3** [comment]
I just didn't have the right intents

**Comment by phamhuuan** [comment]
@aradclash3 I have the same problem, what intents you was missing?
