### ISSUE TITLE
Args not giving out arguments properly

### ISSUE THREAD

**Issue by NichuNaizam** [AlexzanderFlores/WOKCommands#16]
when i give input like` !purge 30`
it gives only 3 as output while running the command in args[0]
pls help and thanks

**Comment by wrssmithjr04** [comment]
What version are you on? And are you pulling it from dev, main, or the npm package?

**Comment by wrssmithjr04** [comment]
After looking at your TeamCord source code it looks as if you have the callback function messed up.

Please replace this:


With this:

**Comment by AlexzanderFlores** [comment]
Hey, you might have the argument order messed up as was previously mentioned. Check out the documentation for WOKCommands here: https://www.npmjs.com/package/wokcommands#creating-a-command

It should be `(message, args, text, client, prefix, instance)`
