### ISSUE TITLE
WOKCommands > Could not find the correct message to send for "SYNTAX_ERROR"

### ISSUE THREAD

**Issue by kcplayz** [AlexzanderFlores/WOKCommands#18]
This error Pops Out when i start or restart the bot

**Comment by wrssmithjr04** [comment]
This happens to anybody on WOKCommands version 1.1.5. We will have to wait till the changes from the main branch is published to the npm package for it to be fixed.

**Comment by AlexzanderFlores** [comment]
Hey, as of version 1.1.9 and above this problem should be fixed. To ensure you have the latest version run `npm install wokcommands@latest`
