### ISSUE TITLE
When following the Episode 5 tutorial, I get an error.

### ISSUE THREAD

**Issue by StupidRepo** [AlexzanderFlores/WOKCommands#187]
I made ping.js and when I run my bot I get this:

`Cannot use import statement outside a module`

Code:

```
import { ICommand } from "wokcommands"

export default {
    category: "Test",
    description: "Pong!",

    callback: ({ message }) => {
        message.reply("Pong!")
    }
} as ICommand 
```

**Comment by qxb3** [comment]
This code is only for typescript, you either use typescript or do 
```javascript
module.exports =  {
    category: "Test",
    description: "Pong!",

    callback: ({ message }) => {
        message.reply("Pong!")
    }
}
```

Follow this tutorials:
[typescript setup](https://youtu.be/JMmUW4d3Noc) 
[wokcommands tutorial](https://youtu.be/J_fJq7zWfWE)

**Comment by 0x414e45** [comment]
If you are with JS you'll need to add 

```js 
{
  // ...
  "type": "module",
  // ...
} 
```
in **package.json**
