### ISSUE TITLE
Don't creating slash commands with russian names

### ISSUE THREAD

**Issue by SkyWatcher2019** [AlexzanderFlores/WOKCommands#196]
```js
import {ICommand} from "wokcommands";
import {MessageEmbed} from "discord.js";

export default {
    name: 'статус',
    description: 'Статус бота',
    category: 'dev',
    slash: 'both',
    callback: ({}) => {
        return new MessageEmbed()
            .setDescription('Статус');
    },
} as ICommand;
```
![image](https://user-images.githubusercontent.com/62600934/145855623-352b7ec7-4b66-433e-8709-aefb89029552.png)
![image](https://user-images.githubusercontent.com/62600934/145855764-66b86aad-0cf7-44e3-9d9d-d09aebbe24df.png)
![image](https://user-images.githubusercontent.com/62600934/145855786-09aeb46e-f27a-492a-a750-4e65dbca0349.png)
![image](https://user-images.githubusercontent.com/62600934/145856110-758459b2-587a-4376-a7e0-6ef8cecd9987.png)

**Comment by gamer167** [comment]
I think I know why. Russian characters (letters) are invalid characters probably. Try making it with English letters and try running it again.

**Comment by SkyWatcher2019** [comment]
> I think I know why. Russian characters (letters) are invalid characters probably. Try making it with English letters and try running it again.

Half-year later, ok. It works fine with English letters.
And I've already stopped using that handler.

**Comment by tippfehlr** [comment]
This is a good decision, this handler isn't the best.
Although it can't do anything about that the characters are diallowed it could check them and throw an error.

Directly from [Discord documentation](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-naming):
> Command names and command option names must match the following regex `^[-_\p{L}\p{N}\p{sc=Deva}\p{sc=Thai}]{1,32}$` with the unicode flag set.

**Comment by SkyWatcher2019** [comment]
> Although it can't do anything about that the characters are diallowed it could check them and throw an error.

![изображение](https://user-images.githubusercontent.com/62600934/173465155-ce1d973c-8c2c-4eb6-8e36-56a40193dc27.png)
![изображение](https://user-images.githubusercontent.com/62600934/173465203-00729b46-57fa-4971-9734-3cfb64edd45d.png)
"аватар" and "бан" commands

**Comment by SkyWatcher2019** [comment]
and directly from disnake
![изображение](https://user-images.githubusercontent.com/62600934/173465374-30a2882b-fa63-4abc-a076-2e4de7cdf434.png)
![изображение](https://user-images.githubusercontent.com/62600934/173465398-ea68a395-26e6-4eda-bad5-fa9749b51b72.png)

**Comment by tippfehlr** [comment]
So it seems to work then?

**Comment by SkyWatcher2019** [comment]
It worked when i opened this issue, This problem only exists in WOKCommands.
