### ISSUE TITLE
Deferring

### ISSUE THREAD

**Issue by Grayson-code** [AlexzanderFlores/WOKCommands#206]
Adding an option to defer an slash command whenever its send and if yes making the return strings work with them

**Comment by ASPNyan** [comment]
If you're saying what I think you are, this is a part of Discord.JS already. Use `interaction.deferReply()`. https://discord.js.org/#/docs/discord.js/stable/class/CommandInteraction?scrollTo=deferReply

You can then run whatever code you want and then just use `interaction.editReply(content)`

**Comment by Grayson-code** [comment]
> If you're saying what I think you are, this is a part of Discord.JS already. Use `interaction.deferReply()`. https://discord.js.org/#/docs/discord.js/stable/class/CommandInteraction?scrollTo=deferReply
> 
> You can then run whatever code you want and then just use `interaction.editReply(content)`

i figured it out long time ago and i dont use wok commands anymore but thanks for solving this.
