### ISSUE TITLE
Language Command Crashed Bot In Dms

### ISSUE THREAD

**Issue by Benzo-Fury** [AlexzanderFlores/WOKCommands#224]
I came across a error in WOK.
The language command (built in one) crashed the bot if used in dms. Would be great to have a feture that returns saying it cannot be used here. Now anyone can crash my bot if they know my secret 😢
![image](https://user-images.githubusercontent.com/80315475/173489362-fbc24713-9151-4bcf-bac3-f2fa40e9b0bb.png)

**Comment by tippfehlr** [comment]
I fixed this in [tippf3hlr/wokcommands](https://github.com/tippf3hlr/wokcommands) but this repository isn't really maintained. If you need this go to your node_modules/wokcommands/ and add the guildonly option to the default commands

**Comment by NeoYaBoi** [comment]
Ahh thank you

**Comment by Benzo-Fury** [comment]
Ahh, thank you.
