### ISSUE TITLE
Use Features of WOKCommands with other Handlers

### ISSUE THREAD

**Issue by NedcloarBR** [AlexzanderFlores/WOKCommands#25]
Good afternoon I use a command handler different than what comes with the module because I think better that I use to do some things and wanted to know how I can integrate to use the multilanguage of the wok with my handler command already tried to use the tutorial Discord JS Language Selector (2020) [Episode #41] 
URL: https://www.youtube.com/watch?v=k-7hby6lDw4&list=PLaxxQQak6D_fxb9_-YsmRwxfw5PH9xALe&index=44 
and did not work and could not arrange the error I tried to ask for help on the server but I could not get the solution!

**Comment by tippfehlr** [comment]
Then you search for javascript translation library and use that.
