### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by cursorsdottsx** [AlexzanderFlores/WOKCommands#33]
For a long while now, users have been asking for TypeScript support.

I think there should be TypeScript support as well.

Instead of require, we can use `(await import(...)).default` if we are using ES6.

Why use import instead? TypeScript can infer types of imports, but not require.

I also think `else if (file.name.endsWith(".js")) {` ought to be replaced by a regex like so:

```ts
const fileNameRegex = /\.[tj]s$/

...
else if (fileNameRegex.test(".js")) {
...
```

**Comment by xCykrix** [comment]
Running this in a TypeScript project is mostly supported. It isn't very easy to get working as of yet, especially in very strict environments, and will require a pretty decent knowledge of Typescript in my opinion. Adding `useTypescript: true` in your WOKCommands options will allow the file indexer to load TypeScript files as long as you have a tool that enabled Node.js to dynamically require ts files such as ts-node.
