### ISSUE TITLE
Cannot find module on Ubuntu

### ISSUE THREAD

**Issue by MaticSulc** [AlexzanderFlores/WOKCommands#40]
I've recently migrated to Ubuntu 20.04 from Windows Server and the package isn't working anymore. 
I've searched through discord and found multiple people having the same issue, for now I've rolled back to windows server but I'd like if it worked on ubuntu as well.

Getting an error:
![image](https://user-images.githubusercontent.com/22326918/110210411-e1e26380-7e91-11eb-9e20-3dc8aca93469.png)

Using example code snippets to reproduce.

**Comment by foopis23** [comment]
Interestingly, I am developing on Windows 10 and I am having this issue as well

**Comment by foopis23** [comment]
Oh! I found a solution that worked for me. I changed my node version from 10.13 to 15.10.

**Comment by tippfehlr** [comment]
Node version 10 isn't supported by discord.js anyways.

**Comment by tippfehlr** [comment]
Close this?

**Comment by foopis23** [comment]
Yes, close this.
