### ISSUE TITLE
Bot Removes Members Reactions from ALL Message Embeds

### ISSUE THREAD

**Issue by alima566** [AlexzanderFlores/WOKCommands#49]
Every time my bot sends an embed and reacts to it, any member that reacts following that will automatically have their reaction removed from the embed. This is not ideal if, for example, you are trying to do a poll or a giveaway command and you NEED to have the members reactions.

**Comment by kakarot-dev** [comment]
They have fixed it in the dev version
Waiting for it to be pushed to the actual package

**Comment by AlexzanderFlores** [comment]
This should be fixed in the latest NPM deployment. To install use "npm install wokcommands@latest"
