### ISSUE TITLE
[enhancement] Configurable Mongoose Options

### ISSUE THREAD

**Issue by chrispiciullo** [AlexzanderFlores/WOKCommands#5]
Good afternoon!

Let me preface this by saying that I "labeled" this an enhancement because I didn't see a way to modify the connection options for mongoose aside from editing mongo.js/ts. I understand that this may not be needed, however, in my case, I need to use a fuzzy search plugin [(Mongoose Fuzzy Searching)](https://github.com/VassilisPallas/mongoose-fuzzy-searching) which requires `useCreateIndex: true` to work.

Would it be possible to add (optional?) configurable settings to the mongoose connection string in future version?

Thanks in advance!

**Comment by AlexzanderFlores** [comment]
Hey, thanks for the suggestion! I've added this to the dev branch. Keep in mind there are some breaking changes in the WOKCommands constructor and command system in the latest dev build. These should be easy to adapt to but will require some changes. See the documentation for more information on the changes as well as how to set the dbOptions property.

**Comment by chrispiciullo** [comment]
Thanks, Alex! I appreciate how fast you added this to WOKCommands. This package is fantastic so far, and I can't wait to see it grow!
