### ISSUE TITLE
wokcommands never sends the EXEPTION from messages.json

### ISSUE THREAD

**Issue by aradclash3** [AlexzanderFlores/WOKCommands#85]
whenever there is an error instead of wokcommands sending the 'an error occurred message it sends the could not find the correct message to send message, sorry if I was a little bit too picky it just doesn't look right

**Comment by JoniKiwi** [comment]
Do you have all messages in message.json defined? Or try this code here: [https://github.com/AlexzanderFlores/WOKCommands/blob/main/src/messages.json](url). It works save.

**Comment by aradclash3** [comment]
yeah, I have it defined

**Comment by aradclash3** [comment]
it got fixed
