### ISSUE TITLE
Slash Commands minArgs

### ISSUE THREAD

**Issue by alima566** [AlexzanderFlores/WOKCommands#94]
I'm trying to add a slash command with optional args (i.e., I want to execute a slash command with or without arguments), however, setting the `minArgs` property to 0, results in the following error:
```
DiscordAPIError: Invalid Form Body
options[0].name: Command name is invalid
    at RequestHandler.execute (/root/Bot/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RequestHandler.push (/root/Bot/node_modules/discord.js/src/rest/RequestHandler.js:39:14) {
  method: 'post',
  path: '/applications/754033907267010560/commands',
  code: 50035,
  httpStatus: 400
}
```
Setting the `minArgs` property to any other number besides 0 or removing it entirely will not result in this error.

**Comment by docentYT** [comment]
The same problem. If I changed `expectedArgs` i don't have error.

**Comment by El-Sashok** [comment]
I had the same problem. I found out a solution : if there is a capital letter in the "expectedArgs" attribute, there will be the crash
